source 'https://rubygems.org'

gem 'rack'
gem 'thor'
gem 'puma'
gem 'roo', '~> 2.7.0'

group :test do
  gem 'rspec'
  gem 'rack-test'
end

group :development do
  gem 'rubocop'
end

group :development, :test do
  gem 'pry'
end
